/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl2;

import org.xtext.example.mydsl2.AbstractMyDsl2RuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDsl2RuntimeModule extends AbstractMyDsl2RuntimeModule {
}
