/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl2.web;

import org.xtext.example.mydsl2.web.AbstractMyDsl2WebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class MyDsl2WebModule extends AbstractMyDsl2WebModule {
}
