/*
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl2.ide


/**
 * Use this class to register ide components.
 */
class MyDsl2IdeModule extends AbstractMyDsl2IdeModule {
}
