/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl1.ide;

import org.xtext.example.mydsl1.ide.AbstractMyDsl1IdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyDsl1IdeModule extends AbstractMyDsl1IdeModule {
}
