/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl2.scoping;

import org.xtext.example.mydsl2.scoping.AbstractMyDsl2ScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class MyDsl2ScopeProvider extends AbstractMyDsl2ScopeProvider {
}
