/*
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl1.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link MyDsl1WebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractMyDsl1WebModule extends DefaultWebModule {

}
