/*
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl1


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MyDsl1StandaloneSetup extends MyDsl1StandaloneSetupGenerated {

	def static void doSetup() {
		new MyDsl1StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
