/*
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl2.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link MyDsl2WebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractMyDsl2WebModule extends DefaultWebModule {

}
