/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl2.ide;

import org.xtext.example.mydsl2.ide.AbstractMyDsl2IdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyDsl2IdeModule extends AbstractMyDsl2IdeModule {
}
