/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl1.validation;

import org.xtext.example.mydsl1.validation.AbstractMyDsl1Validator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MyDsl1Validator extends AbstractMyDsl1Validator {
}
