/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl1;

import org.xtext.example.mydsl1.AbstractMyDsl1RuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDsl1RuntimeModule extends AbstractMyDsl1RuntimeModule {
}
