/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl1;

import org.xtext.example.mydsl1.MyDsl1StandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDsl1StandaloneSetup extends MyDsl1StandaloneSetupGenerated {
  public static void doSetup() {
    new MyDsl1StandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
