/*
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl1.ide


/**
 * Use this class to register ide components.
 */
class MyDsl1IdeModule extends AbstractMyDsl1IdeModule {
}
