/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl1.web;

import org.xtext.example.mydsl1.web.AbstractMyDsl1WebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class MyDsl1WebModule extends AbstractMyDsl1WebModule {
}
